export type Tab = 'departments' | 'units' | 'designations' | 'staff' | 'atms' | 'partners' | 'assets' | 'lockers' | 'bulletins' | 'misUpload' | 'budgets' | 'registry' | 'auditLog' | 'command' | 'organization';

export interface MasterItem {
    id?: string;
    nameEn?: string;
    fullNameEn?: string;
    nameTa?: string;
    fullNameTa?: string;
    nameHi?: string;
    fullNameHi?: string;
    designationEn?: string;
    designationTa?: string;
    designationHi?: string;
    code?: string;
    username?: string;
    type?: string;
    openDate?: string;
    populationGroup?: string;
    address?: string;
    addressTa?: string;
    addressHi?: string;
    phone?: string;
    email?: string;
    riskCategory?: string;
    riskEffectiveDate?: string;
    prevRiskCategory?: string;
    micr?: string;
    bsrCode?: string;
    address1En?: string;
    address2En?: string;
    districtEn?: string;
    address1Ta?: string;
    address2Ta?: string;
    districtTa?: string;
    address1Hi?: string;
    address2Hi?: string;
    districtHi?: string;
    latitude?: number;
    longitude?: number;
    specialStatus?: string | string[];
    gender?: string;
    officeId?: number;
    workId?: number;
    role?: string;
    grade?: string;
    designationId?: string;
    branchId?: string;
    sealPath?: string;
    departmentId?: string;
    departmentIds?: string[];
    managedDepartmentIds?: string[];
    isUnitHead?: boolean;
    isSecondLine?: boolean;
    designation?: { nameEn: string };
    branch?: { nameEn: string, headUserId?: string, secondLineUserId?: string, type?: string };
    department?: { nameEn: string };
    departments?: { id: string, nameEn: string }[];
    managedDepartments?: { id: string, nameEn: string }[];
    photo?: { data: string };
    photoData?: string | ArrayBuffer | null;
    atmId?: string;
    deviceType?: string;
    managementType?: string;
    locationType?: string;
    lastTxnTime?: string;
    balance?: number;
    size?: string;
    pincode?: string;
    ifsc?: string;
    registrationNo?: string;
    category?: string;
    assetCode?: string;
    description?: string;
    purchaseDate?: string;
    purchaseValue?: number;
    condition?: string;
    amcExpiry?: string;
    lockerNo?: string;
}

export interface TabGroup {
    name: string;
    icon: any;
    tabs: {
        id: Tab;
        label: string;
        icon: any;
    }[];
}
