export const quillModules = {
    toolbar: [
        [{ 'header': [1, 2, 3, false] }],
        ['bold', 'italic', 'underline', 'strike'],
        [{ 'list': 'ordered' }, { 'list': 'bullet' }],
        [{ 'color': [] }, { 'background': [] }],
        ['link', 'table'],
        ['clean']
    ],
};

export const quillStyle = `
  .quill { 
    background: white;
    border-radius: 0.75rem;
    overflow: hidden;
    border: 2px solid #f3f4f6 !important;
  }
  .ql-toolbar { 
    border: none !important; 
    border-bottom: 2px solid #f3f4f6 !important; 
    background: #f9fafb;
  }
  .ql-container { 
    border: none !important;
    min-height: 150px;
    font-family: inherit;
  }
  .ql-editor { 
    font-size: 0.875rem;
    line-height: 1.6;
    color: #1e293b;
  }
  .ql-editor.ql-blank::before {
    color: #9ca3af;
    font-style: normal;
  }
`;

export const INITIAL_FORM = {
    type: 'CUSTOM',
    titleEn: '',
    titleTa: '',
    titleHi: '',
    deptName: '',
    referenceNo: '',
    preparerId: '',
    approverId: '',
    reviewerIds: [],
    contentJson: {
        details: '',
        amount: '',
        branch: '',
        justification: '',
        reference: '',
        dateOfOpening: '',
        branchName: '',
        permissionDetails: '',
        populationCategory: 'RURAL',
        populationCentre: '',
        communityBlock: '',
        talukTehsil: '',
        districtState: '',
        workingHours: '',
        branchCode: '',
        postalAddress: '',
        currencyChest: '',
        authorisedDealer: '',
        underCBS: 'Yes',
        micrCode: '',
        ifscCode: '',
        cbsCode: '',
        addressLine1: '',
        addressLine2: '',
        postOfficeName: '',
        pinCode: '',
        longitude: '',
        latitude: '',
        telNo: '',
        mobileNo: '',
        faxNo: '',
        emailAddress: '',
        revenueCentre: '',
        workingHoursWeekdays: '',
        workingHoursSaturdays: '',
        workingHoursHoliday: '',
        postalAddressWithPin: '',
        isUnderCBS: 'Yes',
        mailId: '',
        landlineNumber: '',
        branchHeadDetails: '',
        controllingOfficeDetails: '',
        applicantName: '',
        applicantAccount: '',
        kycCompliance: 'Yes',
        dateOfIssue: '',
        instrumentDetails: '',
        beneficiaryName: '',
        beneficiaryAccount: '',
        beneficiaryBankBranch: '',
        ddFavouring: '',
        ddDrawnOn: '',
        purpose: '',
        transactionId: '',
        noteDate: '',
        branchSol: '',
        branchHeadGrade: '',
        issuingBranch: '',
        policyCirculars: [{ dept: 'Central Office, Dept. of GAD', date: '', ref: '' }] as {dept: string, date: string, ref: string}[],
        glAccountNo: '',
        glAccountDesc: '',
        glOwnershipDept: '',
        glOperationUser: '',
        glPurpose: '',
        glOpType: 'Both',
        glDrCrBoth: 'Both',
        glAssetLiability: 'Liability',
        glActivity: 'Generic',
        glLimits: 'No',
        glMonitoringDept: 'RO Accounts',
        glOperationBy: 'Branch only',
        glCashOp: 'No',
        glReconMandate: 'Reconciliation to zero by same day',
        rbi_action: 'ADDITION' as string,
        rbi_updatePartICode: '',
        rbi_updateEffectiveDate: '',
        rbi_conversionFrom: '',
        rbi_conversionTo: '',
        rbi_conversionPartICode: '',
        rbi_conversionDate: '',
        rbi_outletClass: 'BM_BRANCH' as string,
        rbi_bmDomesticOverseas: 'DOMESTIC' as string,
        rbi_bcType: 'CORPORATE' as string,
        rbi_bcBasePartICode: '',
        rbi_bcIBARegNo: '',
        rbi_officeDomesticOverseas: 'DOMESTIC' as string,
        rbi_officeType: '',
        rbi_officeTypeOther: '',
        rbi_officeBasePartICode: '',
        rbi_naioType: '',
        rbi_naioTypeOther: '',
        rbi_naioBasePartICode: '',
        rbi_cspMode: '',
        rbi_cspModeOther: '',
        rbi_cspOnsiteOffsite: 'ONSITE' as string,
        rbi_cspBasePartICode: '',
        rbi_outletName: '',
        rbi_applicableCategory: 'GENERAL_PERMISSION' as string,
        rbi_licenceNo: '',
        rbi_licenceDate: '',
        rbi_revalidationRef: '',
        rbi_revalidationDate: '',
        rbi_dateOfOpening: '',
        rbi_currencyChestPartICode: '',
        rbi_micrCode: '',
        rbi_ifscCode: '',
        rbi_cbsCode: '',
        rbi_country: 'India',
        rbi_state: '',
        rbi_district: '',
        rbi_subDistrict: '',
        rbi_revenueCentre: '',
        rbi_addressLine1: '',
        rbi_addressLine2: '',
        rbi_postOfficeName: '',
        rbi_pinCode: '',
        rbi_longitude: '',
        rbi_latitude: '',
        rbi_bcContactName: '',
        rbi_telephone: '',
        rbi_mobile: '',
        rbi_fax: '',
        rbi_email: '',
        rbi_workingType: 'FULL_TIME' as string,
        rbi_fullTimeHours: '',
        rbi_schedule: {
            allDays:   { from: '', to: '', from2: '', to2: '' },
            monday:    { from: '', to: '', from2: '', to2: '' },
            tuesday:   { from: '', to: '', from2: '', to2: '' },
            wednesday: { from: '', to: '', from2: '', to2: '' },
            thursday:  { from: '', to: '', from2: '', to2: '' },
            friday:    { from: '', to: '', from2: '', to2: '' },
            saturday:  { from: '', to: '', from2: '', to2: '' },
            sunday:    { from: '', to: '', from2: '', to2: '' },
        } as Record<string, Record<string, string>>,
        rbi_additionalCentres: '',
        rbi_services: {
            generalBanking: false,
            personalBanking: false,
            electronicSelfService: false,
            lockerFacility: false,
            moneyTransfer: false,
            currencyChest: false,
            smallCoinDepot: false,
            agriFinance: false,
            msmeFinance: false,
            otherCorporateFinance: false,
            forexBusiness: false,
            merchantBanking: false,
            shareTrading: false,
            mutualFund: false,
            lifeInsurance: false,
            nonLifeInsurance: false,
            ppfAccounts: false,
            pensionAccounts: false,
            frankingServices: false,
            taxCollection: false,
            treasuryAdmin: false,
            forexTreasury: false,
            forexOfficeA: false,
            forexOfficeB: false,
            govtPension: false,
            currencyChestAdmin: false,
            assetRecovery: false,
            clearingPayments: false,
            processingCentres: false,
            adminHO: false,
            otherServices: '',
        } as Record<string, any>,
        rbi_forexADCategory: '',
        rbi_forexAuthDate: '',
        rbi_forexSettlingPartICode: '',
        rbi_cspManned: 'MANNED' as string,
        rbi_remarks: '',
        expenseCategory: 'REVENUE' as string,
        budgetHead: '',
        budgetAllocated: '',
        budgetUtilized: '',
        proposedAmount: '',
        vendorName: '',
        vendorPan: '',
        vendorGst: '',
        tdsApplicable: 'Yes' as string,
        gstApplicable: 'Yes' as string,
        quotationBasis: 'L1' as string,
        quotationDetails: '',
        expensePurpose: '',
        recommendation: '',
        cifId: '',
        tdAccountNo: '',
        depositorType: 'Individual' as string,
        customerDob: '',
        customerAge: '',
        depositOpenDate: '',
        contractRate: '',
        brokenPeriodStart: '',
        brokenPeriodEnd: '',
        brokenPeriodDays: '',
        principalAmount: '',
        claimedInterestRate: '',
        customerCategory: 'General' as string,
        additionalSpread: '0' as string,
        effectiveInterestRate: '',
        compoundingFrequency: 'SIMPLE' as string,
        calculatedInterest: '',
        brokenPeriodJustification: '',
        revCustomerName: '',
        revAccountNumber: '',
        revCifId: '',
        revChargeType: 'SMS Charges' as string,
        revOriginalChargeDate: '',
        revOriginalChargeAmount: '',
        revReversalAmount: '',
        revReason: 'Bank Error' as string,
        revJustification: '',
        glFinacleMandatory: 'Yes' as string,
        glPointerFacility: 'Yes' as string,
        glRevokeStatus: '',
        glRoPower: 'No' as string,
        glReconZeroEod: 'No' as string,
        scope: 'BRANCH' as string,
        regionName: 'Dindigul Region' as string,
    }
};
